---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: octavia-ca-passphrase
    literals:
      - server-ca-passphrase=12345678
    options:
      disableNameSuffixHash: true

components:
  - ../../../../dt/bgp/

resources:
  - nncp/values.yaml
  - service-values.yaml
