---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovs-dpdk-sriov-cpu-pinning-nova
data:
  25-cpu-pinning-nova.conf: _replaced_
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriov-nova
data:
  03-sriov-nova.conf: _replaced_
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova-custom-ovsdpdk
spec:
  label: nova-custom-ovsdpdk
  configMaps:
    - ovs-dpdk-sriov-cpu-pinning-nova
    - sriov-nova
  secrets:
    - nova-cell1-compute-config
    - nova-migration-ssh-key
  playbook: osp.edpm.nova
