---
name: Run yaml-lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - stable
    paths:
      - "**.yaml"
      - "**.yml"
      - test-kustomizations.sh

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install yaml-lint
        run: pip install yamllint

      - name: Run yaml-lint
        run: yamllint -c .yamllint.yml -s .

  test-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Run test-kustomization script
        run: ./test-kustomizations.sh examples/
